"""
10 mock BOL records using real field formats and real data scale from
the production spreadsheet (Technique and BOL Numbers New June 2026.xlsx).

Covers every UI state the dashboard must handle:
  - Records with and without BOL numbers (BOL is nullable until created in Prophecy)
  - Records with null trip/manifest (blank rows in Excel belong to trip above)
  - Cost % green / yellow / red ranges
  - Null amount (invoice not yet received)
  - CM_ comingle manifest prefix (future Module 2 marker)
  - "cancels out" notes
  - Approved, pending, and flagged statuses
  - Type A (needs_sid_export=True) vs Type B (bol_number exists, needs_sid_export=False)
  - Records 13–14: no_invoice=True for third-party button testing
"""
from datetime import datetime, timezone
from decimal import Decimal

MOCK_BOLS = [
    {
        "id": "aaaaaaaa-0001-0001-0001-000000000001",
        "bol_number": None,
        "technique_trip": "TEC_T_0109878",
        "manifest": "TEC_M_0228920",
        "technique_weight": Decimal("30074.00"),
        "technique_pallets": 42,
        "technique_pcs": 343521,
        "invoice_number": "Z555216",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("3258.15"),
        "access_prog": Decimal("3177.77"),
        "amount": Decimal("3139.85"),
        "cost_pct": Decimal("0.988076"),   # 98.81% — green
        "base_tariff": Decimal("2328.26"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("30237.00"),
        "weight_diff": Decimal("163.00"),
        "prophecy_pallets": 42,
        "pallet_diff": 0,
        "prophecy_pcs": 343521,
        "pcs_diff": 0,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 0, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0002-0002-0002-000000000002",
        "bol_number": None,
        "technique_trip": "TEC_T_0109879",
        "manifest": "TEC_M_0228921",
        "technique_weight": Decimal("21104.00"),
        "technique_pallets": 95,
        "technique_pcs": 405063,
        "invoice_number": "Z555217",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("2764.35"),
        "access_prog": Decimal("3155.38"),
        "amount": Decimal("2806.27"),
        "cost_pct": Decimal("0.889421"),   # 88.94% — red (>10% below)
        "base_tariff": Decimal("2311.27"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("20479.00"),
        "weight_diff": Decimal("-625.00"),
        "prophecy_pallets": 92,
        "pallet_diff": -3,
        "prophecy_pcs": 391764,
        "pcs_diff": -13299,
        "notes": "cancels out",
        "status": "flagged",
        "flag_reason": "ALG invoice vs Access Prog variance exceeds 10% — weight and pallet count discrepancies",
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 1, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 8, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0003-0003-0003-000000000003",
        "bol_number": 145538,
        "technique_trip": "TEC_T_0109880",
        "manifest": None,   # blank in Excel — belongs to trip above
        "technique_weight": Decimal("12772.00"),
        "technique_pallets": 39,
        "technique_pcs": 244940,
        "invoice_number": "Z555218",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("1446.82"),
        "access_prog": Decimal("1496.88"),
        "amount": Decimal("1484.48"),
        "cost_pct": Decimal("0.991714"),   # 99.17% — green
        "base_tariff": Decimal("1096.64"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("12881.00"),
        "weight_diff": Decimal("109.00"),
        "prophecy_pallets": 39,
        "pallet_diff": 0,
        "prophecy_pcs": 244940,
        "pcs_diff": 0,
        "notes": None,
        "status": "approved",
        "flag_reason": None,
        "approved_at": datetime(2026, 6, 10, 10, 15, 0, tzinfo=timezone.utc),
        "approved_by": "coordinator",
        "needs_sid_export": False,  # Type B — bol_number 145538 already exists
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 2, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 10, 15, 0, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0004-0004-0004-000000000004",
        "bol_number": None,
        "technique_trip": "TEC_T_0109881",
        "manifest": "TEC_M_0228923",
        "technique_weight": Decimal("11787.00"),
        "technique_pallets": 56,
        "technique_pcs": 242905,
        "invoice_number": "Z555219",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("1593.85"),
        "access_prog": Decimal("1834.57"),
        "amount": Decimal("1696.34"),
        "cost_pct": Decimal("0.924687"),   # 92.47% — yellow (5–10% below)
        "base_tariff": Decimal("1343.65"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("11869.00"),
        "weight_diff": Decimal("82.00"),
        "prophecy_pallets": 56,
        "pallet_diff": 0,
        "prophecy_pcs": 242905,
        "pcs_diff": 0,
        "notes": "cancels out",
        "status": "flagged",
        "flag_reason": "Cost % below 95% — Access Prog significantly higher than invoice amount",
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 3, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 45, 0, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0005-0005-0005-000000000005",
        "bol_number": None,
        "technique_trip": "TEC_T_0109882",
        "manifest": "TEC_M_0228924",
        "technique_weight": Decimal("15681.00"),
        "technique_pallets": 64,
        "technique_pcs": 370796,
        "invoice_number": "Z555220",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("1918.57"),
        "access_prog": Decimal("2027.76"),
        "amount": Decimal("1935.13"),
        "cost_pct": Decimal("0.954547"),   # 95.45% — green (within 5%)
        "base_tariff": Decimal("1485.13"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("15322.00"),
        "weight_diff": Decimal("-359.00"),
        "prophecy_pallets": 63,
        "pallet_diff": -1,
        "prophecy_pcs": 361603,
        "pcs_diff": -9193,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 4, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 4, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0006-0006-0006-000000000006",
        "bol_number": None,
        "technique_trip": "TEC_T_0109883",
        "manifest": "TEC_M_0228925",
        "technique_weight": Decimal("34304.00"),
        "technique_pallets": 136,
        "technique_pcs": 532126,
        "invoice_number": "Z555221",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("3051.01"),
        "access_prog": Decimal("4764.08"),
        "amount": Decimal("4501.57"),
        "cost_pct": Decimal("0.944898"),   # 94.49% — yellow
        "base_tariff": Decimal("3490.46"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("34522.00"),
        "weight_diff": Decimal("218.00"),
        "prophecy_pallets": 136,
        "pallet_diff": 0,
        "prophecy_pcs": 532126,
        "pcs_diff": 0,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 5, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 5, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0007-0007-0007-000000000007",
        "bol_number": 145572,
        "technique_trip": "TEC_T_0109884",
        "manifest": "CM_052926A",   # CM_ = comingle manifest (future Module 2)
        "technique_weight": Decimal("39813.00"),
        "technique_pallets": 149,
        "technique_pcs": 635641,
        "invoice_number": "Z555222",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("3966.84"),
        "access_prog": Decimal("5692.42"),
        "amount": Decimal("5751.56"),
        "cost_pct": Decimal("1.010389"),   # 101.04% — green
        "base_tariff": Decimal("4170.42"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("398013.00"),
        "weight_diff": Decimal("358200.00"),   # large diff — data entry error in source
        "prophecy_pallets": 149,
        "pallet_diff": 0,
        "prophecy_pcs": 635641,
        "pcs_diff": 0,
        "notes": None,
        "status": "approved",
        "flag_reason": None,
        "approved_at": datetime(2026, 6, 10, 10, 30, 0, tzinfo=timezone.utc),
        "approved_by": "coordinator",
        "needs_sid_export": False,  # Type B — bol_number 145572 already exists
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 6, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 10, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0008-0008-0008-000000000008",
        "bol_number": None,
        "technique_trip": None,   # blank in Excel
        "manifest": None,         # blank in Excel
        "technique_weight": Decimal("42416.00"),
        "technique_pallets": 84,
        "technique_pcs": 673408,
        "invoice_number": "Z555223",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("2825.07"),
        "access_prog": Decimal("4053.93"),
        "amount": Decimal("4096.40"),
        "cost_pct": Decimal("1.010477"),   # 101.05% — green
        "base_tariff": Decimal("2970.50"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("42415.00"),
        "weight_diff": Decimal("-1.00"),
        "prophecy_pallets": 84,
        "pallet_diff": 0,
        "prophecy_pcs": 673408,
        "pcs_diff": 0,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 7, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 7, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0009-0009-0009-000000000009",
        "bol_number": 145574,
        "technique_trip": "TEC_T_0109886",
        "manifest": "TEC_M_0228928",
        "technique_weight": Decimal("23398.00"),
        "technique_pallets": 90,
        "technique_pcs": 419956,
        "invoice_number": "Z555224",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("1706.80"),
        "access_prog": Decimal("2599.69"),
        "amount": Decimal("2506.75"),
        "cost_pct": Decimal("0.964250"),   # 96.43% — green
        "base_tariff": Decimal("1904.19"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("23541.00"),
        "weight_diff": Decimal("143.00"),
        "prophecy_pallets": 90,
        "pallet_diff": 0,
        "prophecy_pcs": 419956,
        "pcs_diff": 0,
        "notes": None,
        "status": "approved",
        "flag_reason": None,
        "approved_at": datetime(2026, 6, 10, 10, 45, 0, tzinfo=timezone.utc),
        "approved_by": "coordinator",
        "needs_sid_export": False,  # Type B — bol_number 145574 already exists
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 8, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 10, 45, 0, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0010-0010-0010-000000000010",
        "bol_number": None,
        "technique_trip": "TEC_T_0109887",
        "manifest": "TEC_M_0228929",
        "technique_weight": Decimal("8765.00"),
        "technique_pallets": 21,
        "technique_pcs": 188518,
        "invoice_number": "Z555225",
        "invoice_email_sender": "Tanya 6/10/2026 4:21PM",
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": Decimal("563.17"),
        "access_prog": Decimal("808.16"),
        "amount": None,       # invoice amount not yet received
        "cost_pct": None,     # cannot compute without amount
        "base_tariff": Decimal("592.01"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("8823.00"),
        "weight_diff": Decimal("58.00"),
        "prophecy_pallets": 21,
        "pallet_diff": 0,
        "prophecy_pcs": 188518,
        "pcs_diff": 0,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 9, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 9, tzinfo=timezone.utc),
    },
    # Records 11 and 12: morning-pull state — no invoice yet.
    # Upload backend/test_data/Z555226_test.csv and Z555227_test.csv to fill these in.
    {
        "id": "aaaaaaaa-0011-0011-0011-000000000011",
        "bol_number": None,
        "technique_trip": "TEC_T_0109888",
        "manifest": "TEC_M_0228930",
        "technique_weight": Decimal("27440.00"),
        "technique_pallets": 76,
        "technique_pcs": 481200,
        "invoice_number": None,               # no Z-number yet — assigned after SID import into Prophecy
        "invoice_email_sender": None,
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": None,
        "access_prog": Decimal("4248.56"),    # base $3,112.50 × (1 + 36.5% FSC)
        "amount": None,
        "cost_pct": None,
        "base_tariff": Decimal("3112.17"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("27620.00"),
        "weight_diff": Decimal("180.00"),
        "prophecy_pallets": 76,
        "pallet_diff": 0,
        "prophecy_pcs": 481200,
        "pcs_diff": 0,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet; will need SID export
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 10, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 10, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0012-0012-0012-000000000012",
        "bol_number": None,
        "technique_trip": "TEC_T_0109889",
        "manifest": "TEC_M_0228931",
        "technique_weight": Decimal("19330.00"),
        "technique_pallets": 58,
        "technique_pcs": 296740,
        "invoice_number": "Z555227",          # Z-number assigned in Prophecy; amount not yet received
        "invoice_email_sender": None,
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": None,
        "access_prog": Decimal("2218.75"),
        "amount": None,
        "cost_pct": None,
        "base_tariff": Decimal("1625.46"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": Decimal("19480.00"),
        "weight_diff": Decimal("150.00"),
        "prophecy_pallets": 58,
        "pallet_diff": 0,
        "prophecy_pcs": 296740,
        "pcs_diff": 0,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,   # Type A — no BOL yet; will need SID export
        "no_invoice": False,
        "is_third_party": False,
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 11, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 11, tzinfo=timezone.utc),
    },
    # Records 13–14: no_invoice=True — customer pays freight directly.
    # Record 13: shows the "3rd Party" button in the pending table.
    # Record 14: pre-seeded as already marked third-party (appears in ThirdPartySection on load).
    {
        "id": "aaaaaaaa-0013-0013-0013-000000000013",
        "bol_number": None,
        "technique_trip": "TEC_T_0109890",
        "manifest": "TEC_M_0228932",
        "technique_weight": Decimal("14210.00"),
        "technique_pallets": 44,
        "technique_pcs": 198600,
        "invoice_number": None,
        "invoice_email_sender": None,
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": None,
        "access_prog": Decimal("1847.32"),
        "amount": None,
        "cost_pct": None,
        "base_tariff": Decimal("1353.17"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": None,
        "weight_diff": None,
        "prophecy_pallets": None,
        "pallet_diff": None,
        "prophecy_pcs": None,
        "pcs_diff": None,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,
        "no_invoice": True,         # customer pays freight — 3rd Party button visible
        "is_third_party": False,    # not yet marked; click "3rd Party" to move it
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 12, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 12, tzinfo=timezone.utc),
    },
    {
        "id": "aaaaaaaa-0014-0014-0014-000000000014",
        "bol_number": None,
        "technique_trip": "TEC_T_0109891",
        "manifest": "TEC_M_0228933",
        "technique_weight": Decimal("9850.00"),
        "technique_pallets": 28,
        "technique_pcs": 124300,
        "invoice_number": None,
        "invoice_email_sender": None,
        "inv_job_number": None,
        "carrier": None,
        "alg_weight": None,
        "alg_pallets": None,
        "alg_pcs": None,
        "prop_reship": None,
        "access_prog": Decimal("1121.45"),
        "amount": None,
        "cost_pct": None,
        "base_tariff": Decimal("821.43"),
        "fsc_pct": Decimal("0.365000"),
        "prophecy_weight": None,
        "weight_diff": None,
        "prophecy_pallets": None,
        "pallet_diff": None,
        "prophecy_pcs": None,
        "pcs_diff": None,
        "notes": None,
        "status": "pending",
        "flag_reason": None,
        "approved_at": None,
        "approved_by": None,
        "needs_sid_export": True,
        "no_invoice": True,         # customer pays freight
        "is_third_party": True,     # pre-seeded in ThirdPartySection for testing
        "match_strategy": None,
        "sid_exported_at": None,
        "accounting_exported_at": None,
        "created_at": datetime(2026, 6, 10, 7, 0, 13, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 6, 10, 7, 0, 13, tzinfo=timezone.utc),
    },
]
